### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by DigiAngel** [fireeye/flare-fakenet-ng#59]
Wanting to just have fakenet respond like inetsim on a virtual interface...how do I tell fakenet to just listen on that interface?  Thanks.

**Comment by garsim** [comment]
Inside the config.ini you must enable, in linux version, the MultiHostMode and then set the option "LinuxRedirectNonLocal" with the name of the right interface (as default you find "*").
In any case I think there is some problem because also when fakenet is setted as multihost then it redirects all the traffic as SingleHost.

**Comment by DigiAngel** [comment]
Thank you!

**Comment by strictlymike** [comment]
The `LinuxRedirectNonlocal` setting strictly concerns redirection of packets destined for _foreign_ hosts. For example, packets destined for hard-coded malware C2 IP addresses or for the foreign IP addresses handed out by `DNSListener`. The setting does not restrict FakeNet-NG's overall purview to a single interface. For that, I have added issue #62.
